format = "$directory$git_status$package$cmd_duration $fill $git_branch$python$nodejs$golang \n $character"
# right_format = '$git_branch$nodejs$python$golang'

scan_timeout = 10
add_newline = true

[fill]
symbol = ' '
style = 'bold green'

[directory]
style = 'bold italic cyan'
read_only = ''
format = '[$read_only]($read_only_style) [$path ]($style)'
truncation_symbol = '.../'

[package]
symbol = ''
style = 'bold 208'
format = '[\[ $symbol $version \]]($style)'

[cmd_duration]
style = 'dimmed yellow'
format = '[\[ $duration \]]($style)'

[git_branch]
symbol = ''
format = '[\[ $symbol $branch \]]($style)'

[git_status]
style = 'bold red'
conflicted = 'c '
untracked = ' '
stashed= 's '
modified = '[ ](yellow)'
staged = '+ '
renamed = 'r '
deleted = 'd '

ahead = ''
behind = ''
diverged = ''
up_to_date = '[](bright-green)'
format = '[\[ ($all_status$ahead_behind) \]]($style) '

[nodejs]
style = 'bold green'
symbol = ''
format = '[\[ $symbol ($version )\]]($style)'

[python]
style = 'bold blue'
symbol = ''
format = '[\[ $symbol ($version( \($virtualenv\)) )\]]($style)'

[golang]
style = 'bold cyan'
symbol = ''
format = '[\[ $symbol ($version) \]]($style)'

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "
