format = '$all'
right_format = '$git_branch$nodejs'

[directory]
style = 'bold italic cyan'
read_only = ''
format = '[$read_only]($read_only_style) [$path]($style) '
truncation_symbol = '.../'

[git_branch]
symbol = ''
format = '[\[ $symbol $branch \]]($style)'

[git_status]
style = 'bold red'
conflicted = 'c '
untracked = ' '
stashed= 's '
modified = '[ ](yellow)'
staged = '+ '
renamed = 'r '
deleted = 'd '

ahead = ''
behind = ''
diverged = ''
up_to_date = '[](bright-green)'
format = '[\[ $all_status$ahead_behind \]]($style) '

[nodejs]
style = 'bold green'
symbol = ''
format = '[\[ $symbol ($version )\]]($style)'

[python]
symbol = " "

[cmd_duration]
style = 'dimmed yellow'
format = '[\[ $duration \]]($style)'

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "
