format = "$directory$git_branch$git_status$cmd_duration $fill $package$python$nodejs$golang$rust \n $character"
# right_format = '$git_branch$nodejs$python$golang'

scan_timeout = 10
add_newline = true

[fill]
symbol = ' '
style = 'bold green'

[directory]
style = 'bold italic cyan'
read_only = ''
format = '[$read_only]($read_only_style) [$path ]($style)'
truncation_symbol = '.../'

[package]
symbol = ''
style = 'bold 208'
format = '[package:\([$version](208)\)](purple) '

[cmd_duration]
style = 'dimmed yellow'
format = '[\[ $duration \]]($style)'

[git_branch]
symbol = ''
format = '[git:\([$branch](yellow)\):]($style)'

[git_status]
style = 'bold red'
conflicted = 'c '
untracked = ' '
stashed= 's '
modified = '[ ](yellow)'
staged = '+ '
renamed = 'r '
deleted = 'd '

ahead = 'a'
behind = 'b'
diverged = 'd'
up_to_date = '[](bright-green)'
format = '[\(($all_status | $ahead_behind) \)]($style) '

[nodejs]
style = 'bold green'
format = '[node:\([$version](bold green)\)](purple)'

[python]
style = 'bold blue'
format = '[python:\([$version](bold blue)\)](purple)'

[golang]
style = 'bold cyan'
format = '[go:\([$version](bold cyan)\)](purple)'

[rust]
style = 'bold red'
format = '[rust:\([$version](bold red)\)](purple)'

[aws]
symbol = "  "

[dart]
symbol = " "

[docker_context]
symbol = " "

[julia]
symbol = " "

[scala]
symbol = " "
